github:
  oauth:
    accessToken: ${GITHUB_OAUTH_ACCESS_TOKEN}
discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}
google:
  spreadsheet:
    id: ${GOOGLE_SPREADSHEET_ID}
spring:
  profiles:
    active: prod